import type { HireId, StaffRole, UnlockKind, UpgradeId } from '../config/balance';

export const TR = {
  title: 'Döner Dükkanı',
  shop: 'Dükkan',
  unlockKind: {
    table: 'Masa',
    spit: 'Döner Ocağı',
    office: 'Yönetim Masası',
    hr: 'İK Masası',
    window: 'Paket Penceresi',
  } satisfies Record<UnlockKind, string>,
  role: {
    cashier: 'Kasiyer',
    carrier: 'Garson',
    cleaner: 'Temizlikçi',
  } satisfies Record<StaffRole, string>,
  upgrade: {
    pSpeed: { name: 'Yürüme Hızı', unit: 'm/sn' },
    pCap: { name: 'Taşıma Kapasitesi', unit: 'adet' },
    price: { name: 'Döner Fiyatı', unit: '' },
    sSpeed: { name: 'Personel Hızı', unit: 'm/sn' },
    sCap: { name: 'Personel Kapasitesi', unit: 'adet' },
  } satisfies Record<UpgradeId, { name: string; unit: string }>,
  panelTitle: 'Yönetim',
  panelSub: 'Parayı işine yatır, dükkan büyüsün.',
  hrTitle: 'İnsan Kaynakları',
  hrSub: 'Eleman al, işler sen yokken de dönsün.',
  hrDecal: 'PERSONEL',
  hire: {
    cashier: { name: 'Kasiyer', desc: 'Kasada durur, müşterilere servis yapar.' },
    carrier: { name: 'Garson', desc: 'Dönerleri ocaktan tezgaha taşır.' },
    cleaner: { name: 'Temizlikçi', desc: 'Masalardaki çöpleri toplar.' },
    cashierWindow: { name: 'Pencere Kasiyeri', desc: 'Paket penceresinde servis yapar.' },
  } satisfies Record<HireId, { name: string; desc: string }>,
  hireBtn: 'İşe Al',
  hired: 'Kadro Tam',
  needsWindow: 'Önce Paket Penceresi',
  staffCount: (n: number, max: number) => `${n}/${max} kişi`,
  hiredToast: (name: string) => `${name} işe başladı!`,
  staffSection: 'Personel Gelişimi',
  max: 'MAKS',
  close: 'Kapat',
  save: {
    copied: 'Kod kopyalandı. Diğer cihazda Kayıt → Kaydı yükle.',
    copyFallback: 'Kopyalanamadı. Kodu seçip kendin kopyala.',
    invalid: 'Kod okunamadı. Kodun tamamını kopyaladığından emin ol.',
    confirm: (money: string, n: number) => `Bu kayıtta ${money} ve ${n} açık bölüm var. Buradaki oyunun yerine geçecek.`,
    confirmBtn: 'Eminim, yükle',
    loadBtn: 'Kaydı yükle',
    noStorage: 'Bu tarayıcı kayıt tutamıyor (gizli sekme olabilir).',
  },
  auth: {
    login: 'Giriş yap',
    register: 'Hesap aç',
    working: 'Bekle…',
    errors: {
      bad_email: 'Geçerli bir e-posta adresi yaz.',
      bad_password: 'Şifre en az 8 karakter olmalı.',
      exists: 'Bu e-postayla zaten hesap var. "Giriş yap" sekmesini dene.',
      wrong: 'E-posta ya da şifre yanlış.',
      too_many: 'Çok fazla deneme yapıldı. 15 dakika sonra tekrar dene.',
      network: 'Sunucuya ulaşılamadı. İnternet bağlantını kontrol et.',
    },
    signedIn: (email: string) => `Hesap: ${email}. Oyunun otomatik kaydediliyor.`,
    signOut: 'Çıkış yap',
    guest: 'Hesapsız oynuyorsun; kayıt sadece bu cihazda.',
    signInCta: 'Giriş yap / Hesap aç',
  },
  soundOn: 'Sesi kapat',
  soundOff: 'Sesi aç',
  unlocked: (name: string) => `${name} açıldı!`,
  offline: (amount: string) => `Sen yokken ${amount} kazandın`,
  soon: 'Yakında',
  driveMark: 'PAKET SERVİS',
  onlineNew: (n: number) => `Yeni online sipariş: ${n} döner`,
  onlineStart: 'Online siparişler başladı! Kuryeler kasadan alıp götürür',
  onlineDone: (net: string, gross: string, fee: string) => `Teslim edildi: +${net} (${gross} − ${fee} kurye)`,
  burgerName: 'Burger Dükkanı',
  burgerSoon: 'Burger Dükkanı çok yakında açılıyor!',
  burgerLocked: 'Önce döner dükkanını tamamla',
  hints: [
    'Tepsideki dönerleri al',
    'Dönerleri tezgaha bırak',
    'Kasaya geç, müşterilere servis yap',
    'Parayı yere dök, ilk masayı aç',
  ],
};
