import type { HireId, ProductKind, ShopId, StaffRole, UnlockKind, UpgradeId } from '../config/balance';

export const TR = {
  title: 'Döner Dükkanı',
  shop: 'Dükkan',
  unlockKind: {
    table: 'Masa',
    producer: 'Makine',
    office: 'Yönetim Masası',
    hr: 'İK Masası',
    window: 'Paket Penceresi',
  } satisfies Record<UnlockKind, string>,
  machine: {
    doner: 'Döner Ocağı',
    burger: 'Izgara',
    fries: 'Fritöz',
    shake: 'Milkshake Makinesi',
  } satisfies Record<ProductKind, string>,
  product: {
    doner: 'döner',
    burger: 'burger',
    fries: 'patates',
    shake: 'milkshake',
  } satisfies Record<ProductKind, string>,
  shopName: {
    doner: 'Döner Dükkanı',
    burger: 'Burger Dükkanı',
  } satisfies Record<ShopId, string>,
  gate: {
    open: 'Yeni şube',
    go: 'Diğer şube',
    goTile: (name: string) => `${name}na git`,
    opened: (name: string) => `${name} açıldı!`,
    idle: (name: string, perMin: string) => `${name} sen yokken dakikada ${perMin} kazanıyor`,
  },
  role: {
    manager: 'Müdür',
    stocker: 'Reyon Görevlisi',
    receptionist: 'Resepsiyonist',
    housekeeper: 'Kat Görevlisi',
    cashier: 'Kasiyer',
    carrier: 'Garson',
    cleaner: 'Temizlikçi',
  } satisfies Record<StaffRole, string>,
  upgrade: {
    pSpeed: { name: 'Yürüme Hızı', unit: 'm/sn' },
    pCap: { name: 'Taşıma Kapasitesi', unit: 'adet' },
    price: { name: 'Döner Fiyatı', unit: '' },
    sSpeed: { name: 'Personel Hızı', unit: 'm/sn' },
    sCap: { name: 'Personel Kapasitesi', unit: 'adet' },
  } satisfies Record<UpgradeId, { name: string; unit: string }>,
  priceName: { doner: 'Döner Fiyatı', burger: 'Menü Fiyatları' } satisfies Record<ShopId, string>,
  panelTitle: 'Yönetim',
  panelSub: 'Parayı işine yatır, dükkan büyüsün.',
  hrTitle: 'İnsan Kaynakları',
  hrSub: 'Eleman al, işler sen yokken de dönsün.',
  hrDecal: 'PERSONEL',
  hire: {
    manager: { name: 'Müdür', desc: 'Eksikleri kapatır; gerekirse eleman alır ya da çıkarır.' },
    stocker: { name: 'Reyon Görevlisi', desc: 'Depodaki kolileri boşalan raflara dizer.' },
    checkout2: { name: '2. Kasa Kasiyeri', desc: 'İkinci kasada ödeme alır.' },
    checkout3: { name: '3. Kasa Kasiyeri', desc: 'Üçüncü kasada ödeme alır.' },
    receptionist: { name: 'Resepsiyonist', desc: 'Resepsiyonda durur, misafirleri odalara yerleştirir.' },
    housekeeper: { name: 'Kat Görevlisi', desc: 'Boşalan odalara havlu götürür, yatağı toplar.' },
    cashier: { name: 'Kasiyer', desc: 'Kasada durur, müşterilere servis yapar.' },
    carrier: { name: 'Garson', desc: 'Eksik ürünü tezgaha taşır, boşken masaları toplar.' },
    cleaner: { name: 'Temizlikçi', desc: 'Masaları toplar, boşken ürün taşır.' },
    cashierWindow: { name: 'Pencere Kasiyeri', desc: 'Paket penceresinde servis yapar.' },
  } satisfies Record<HireId, { name: string; desc: string }>,
  hireBtn: 'İşe Al',
  hired: 'Kadro Tam',
  needsWindow: 'Önce Paket Penceresi',
  staffCount: (n: number, max: number) => `${n}/${max} kişi`,
  staffCountOpen: (n: number) => `${n} kişi`,
  hiredToast: (name: string) => `${name} işe başladı!`,
  firedToast: (name: string) => `${name} işten çıkarıldı`,
  managerHired: (name: string) => `Müdür yeni bir ${name.toLocaleLowerCase('tr-TR')} işe aldı`,
  managerFired: (name: string) => `Müdür bir ${name.toLocaleLowerCase('tr-TR')} çıkardı: işi azdı`,
  bossSeat: 'PATRON',
  fireBtn: 'Çıkar',
  fireConfirm: 'Emin misin?',
  staffSection: 'Personel Gelişimi',
  kitchenSection: (used: number, total: number) => `Mutfak · ${used}/${total} makine`,
  addMachine: (name: string) => `${name} ekle`,
  machineDesc: 'Aynı üründen daha hızlı üretim.',
  noRoom: 'Yer yok',
  machineCount: (n: number) => `${n} adet`,
  machineAdded: (name: string) => `Yeni ${name} kuruldu!`,
  max: 'MAKS',
  close: 'Kapat',
  save: {
    copied: 'Kod kopyalandı. Diğer cihazda Kayıt → Kaydı yükle.',
    copyFallback: 'Kopyalanamadı. Kodu seçip kendin kopyala.',
    invalid: 'Kod okunamadı. Kodun tamamını kopyaladığından emin ol.',
    confirm: (money: string, n: number) => `Bu kayıtta ${money} ve ${n} açık bölüm var. Buradaki oyunun yerine geçecek.`,
    confirmBtn: 'Eminim, yükle',
    loadBtn: 'Kaydı yükle',
    noStorage: 'Bu tarayıcı kayıt tutamıyor (gizli sekme olabilir).',
  },
  auth: {
    login: 'Giriş yap',
    register: 'Hesap aç',
    working: 'Bekle…',
    errors: {
      bad_email: 'Geçerli bir e-posta adresi yaz.',
      bad_password: 'Şifre en az 8 karakter olmalı.',
      exists: 'Bu e-postayla zaten hesap var. "Giriş yap" sekmesini dene.',
      wrong: 'E-posta ya da şifre yanlış.',
      too_many: 'Çok fazla deneme yapıldı. 15 dakika sonra tekrar dene.',
      network: 'Sunucuya ulaşılamadı. İnternet bağlantını kontrol et.',
    },
    signedIn: (email: string) => `Hesap: ${email}. Oyunun otomatik kaydediliyor.`,
    signOut: 'Çıkış yap',
    guest: 'Hesapsız oynuyorsun; kayıt sadece bu cihazda.',
    signInCta: 'Giriş yap / Hesap aç',
  },
  city: {
    name: {
      cafe: 'Köşe Kahvecisi',
      barber: 'Usta Berber',
      pide: 'Karadeniz Pide',
      gym: 'Merkez Spor Salonu',
      bank: 'Şehir Bankası',
    },
    about: {
      cafe: 'Bir çay molası, bir kahve keyfi.',
      barber: 'Saç ve sakal. Bakımlı esnafa bahşiş bol olur.',
      pide: 'Taş fırından sıcak pide.',
      gym: 'Günlük antrenman. Çıkınca daha hızlısın.',
    } as Record<string, string>,
    activity: {
      tea: 'Demli çay',
      coffee: 'Türk kahvesi',
      haircut: 'Saç kesimi',
      pide: 'Kıymalı pide',
      workout: 'Antrenman',
    } as Record<string, string>,
    effect: {
      speed: (pct: number, min: number) => `${min} dk boyunca %${pct} daha hızlı yürürsün`,
      carry: (n: number, min: number) => `${min} dk boyunca ${n} fazla taşırsın`,
      tips: (pct: number, min: number) => `${min} dk boyunca müşteriler %${pct} bahşiş bırakır`,
    },
    buffChip: { speed: 'Hız', carry: 'Taşıma', tips: 'Bahşiş' },
    enter: 'GİR',
    busy: (what: string, secs: number) => `${what}… ${secs} sn`,
    done: (what: string) => `${what} bitti!`,
    duration: (secs: number) => `${secs} sn`,
    forSale: 'SATILIK',
    forSaleSub: 'Burger dükkanı için ideal',
    plotLabel: 'Burger Dükkanı',
  },
  market: {
    name: 'Semt Market',
    stockroom: 'DEPO',
    progress: 'Market',
    forSaleSub: 'Süpermarket için ideal',
    plotLabel: 'Süpermarket',
    sign: 'MARKET',
    opened: 'Semt Market açıldı! Depodaki kolileri raflara diz.',
    product: {
      bread: 'ekmek', milk: 'süt', eggs: 'yumurta', pasta: 'makarna', oil: 'ayçiçek yağı', detergent: 'deterjan',
    } as Record<string, string>,
    empty: (what: string) => `Rafta ${what} yok!`,
    needsCheckout: 'Önce kasayı aç',
    unlock: {
      row: (i: number) => `${i + 1}. Reyon`,
      checkout: (i: number) => `${i + 1}. Kasa`,
      desk: () => 'Personel Masası',
    },
    hrSub: 'Kasiyer kasada durur, reyon görevlisi rafları doldurur.',
    truck: (amount: string) => `Toptancı kamyonu geldi: ${amount} mal`,
  },
  hotel: {
    name: 'Grand Lale Otel',
    plotLabel: '5★ Otel',
    forSaleSub: '5 yıldızlı otel için ideal',
    opened: 'Grand Lale Otel açıldı! Misafir çıkınca odaya havlu götür, yatağı topla.',
    hrSub: 'Resepsiyonist misafir karşılar, kat görevlileri odaları hazırlar.',
    progress: 'Otel',
    spaSign: 'SPA',
    noRoom: 'Boş oda yok, gitti',
    roomReady: 'Oda hazır',
    amenity: (name: string, pct: number) => `${name} açıldı! Oda fiyatları %${pct} arttı`,
    unlock: {
      room: (num: number, suite: boolean) => `${suite ? 'Süit' : 'Oda'} ${num}`,
      desk: () => 'Personel Masası',
      buffet: () => 'Kahvaltı Büfesi',
      spa: () => 'Havuz & Spa',
      floor: () => 'Üst Kat',
      terrace: () => 'Teras Bar',
    },
    lift: 'ASANSÖR',
    floorOpened: 'Üst kat açıldı! Asansörün üstünde durup yukarı çık.',
    upstairs: '2. Kat',
  },
  borsa: {
    title: 'Şehir Borsası',
    sub: 'Hisse al, sat; kendi şirketlerini halka arz et.',
    enter: 'BORSA',
    cash: 'Nakit',
    portfolio: 'Portföy',
    own: 'Şirketlerin',
    market: 'Hisseler',
    owned: (pct: string) => `Sende %${pct}`,
    publicPart: (pct: string) => `Halka açık %${pct}: kârın bu kısmı yatırımcıların`,
    notPublic: 'Henüz halka açık değil. Arz edince nakit gelir, kârın o kadarı yatırımcılara gider.',
    value: (v: string) => `Şirket değeri ${v}`,
    ipo: (pct: number) => `%${pct} arz et`,
    buyback: (pct: number) => `%${pct} geri al`,
    maxFloat: 'Kontrol sende kalmalı: en çok %49 halka açılabilir.',
    buy: (amt: string) => `Al ${amt}`,
    sellAll: 'Hepsini sat',
    sellHalf: 'Yarısını sat',
    holding: (n: string, pl: string) => `${n} lot · ${pl}`,
    noHolding: 'Hissen yok',
    ipoDone: (name: string, amt: string) => `${name} halka arz edildi: ${amt} kasaya girdi`,
    buybackDone: (name: string, amt: string) => `${name} hisseleri geri alındı: ${amt}`,
    fees: 'Arzda aracı kurum ve kurul masrafı %5, işlemlerde komisyon ‰2.',
    company: {
      doner: 'Döner Dükkanı', burger: 'Burger Dükkanı', market: 'Semt Market',
      holding: 'Anadolu Holding', energy: 'Marmara Enerji', bank: 'Şehir Bankası',
      pide: 'Karadeniz Pide', gym: 'Merkez Spor', cafe: 'Köşe Kahvecisi', barber: 'Usta Berber',
      hotel: 'Grand Lale Otel',
    } as Record<string, string>,
  },
  patience: {
    left: 'Beklemekten sıkılıp gitti',
    courierLeft: 'Kurye beklemekten vazgeçti, sipariş iptal',
  },
  soundOn: 'Sesi kapat',
  soundOff: 'Sesi aç',
  unlocked: (name: string) => `${name} açıldı!`,
  offline: (amount: string) => `Sen yokken ${amount} kazandın`,
  soon: 'Yakında',
  driveMark: 'PAKET SERVİS',
  onlineNew: (items: string) => `Yeni online sipariş: ${items}`,
  onlineStart: 'Online siparişler başladı! Kuryeler kasadan alıp götürür',
  onlineDone: (net: string, gross: string, fee: string) => `Teslim edildi: +${net} (${gross} − ${fee} kurye)`,
  goals: {
    label: (n: number) => `Hedef ${n}`,
    claim: 'Ödülü al',
    reward: (amt: string) => `Ödül ${amt}`,
    claimed: (amt: string) => `Hedef tamam! +${amt}`,
    title: 'Hedefler',
    sub: 'Her hedef bir sonrakini açar. Bitince karta dokun, ödülünü al.',
    doneCount: (n: number) => `${n} hedef tamamlandı`,
    next: 'Sıradakiler',
    open: 'Hedefleri göster',
  },
  events: {
    rush: { name: 'Öğle yoğunluğu', start: 'Öğle yoğunluğu başladı! Müşteriler akın ediyor', note: 'Müşteri 2 kat' },
    match: { name: 'Maç akşamı', start: 'Maç akşamı! Online siparişler yağıyor', note: 'Online sipariş 4 kat' },
    rain: { name: 'Yağmur', start: 'Yağmur başladı: dükkana az kişi gelir ama online sipariş artar', note: 'Online sipariş artar' },
    payday: { name: 'Maaş günü', start: 'Maaş günü! 30 saniye boyunca her satış 2 kat', note: 'Satışlar 2 kat' },
    vip: {
      name: 'Ünlü müşteri',
      start: 'Ünlü bir müşteri geldi! Beklettirme, 5 kat öder',
      note: 'Altın yıldızlı müşteri',
      arrived: (shop: string) => `${shop}na ünlü bir müşteri geliyor! Beklettirme, 5 kat öder`,
      served: (amt: string) => `Ünlü müşteri çok memnun kaldı: +${amt}`,
      left: 'Ünlü müşteri beklemekten sıkılıp gitti',
    },
    inspection: {
      name: 'Belediye denetimi',
      start: 'Belediye denetimi! Süre bitene kadar masaları temiz tut',
      note: 'Masaları temiz tut',
      dirty: (n: number) => (n ? `${n} kirli masa` : 'Masalar temiz'),
      pass: (amt: string) => `Denetimden tam not aldın: +${amt} teşvik`,
      fail: (n: number, amt: string) => `Denetçi ${n} kirli masa buldu: ${amt} ceza`,
    },
    left: (secs: number) => `${Math.floor(secs / 60)}:${String(Math.floor(secs % 60)).padStart(2, '0')}`,
  },
  hints: [
    'Tepsideki dönerleri al',
    'Dönerleri tezgaha bırak',
    'Kasaya geç, müşterilere servis yap',
    'Parayı yere dök, ilk masayı aç',
  ],
};
